# Generated by Django 4.2.2 on 2023-07-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_user'),
        ('product', '0002_alter_product_enteredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Enteredby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
        ),
    ]
