# Generated by Django 4.2.2 on 2023-07-31 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(5.0)]),
        ),
    ]
