# Generated by Django 4.2.2 on 2023-07-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_enteredby'),
        ('deals', '0002_alter_deals_enteredby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='Price_per_item',
        ),
        migrations.AddField(
            model_name='deals',
            name='Product_price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productprice', to='product.product'),
        ),
    ]
