# Generated by Django 4.2.2 on 2023-07-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_remove_deals_price_per_item_deals_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='Product_price',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='Total',
        ),
    ]
