# Generated by Django 4.2.2 on 2023-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_remove_deals_product_price_remove_deals_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
