# Generated by Django 4.2.2 on 2023-07-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deals_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
