# Generated by Django 4.2.2 on 2023-07-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_alter_deals_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='date',
        ),
        migrations.AddField(
            model_name='deals',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
