# Generated by Django 4.2.2 on 2023-07-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_remove_deals_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='Date',
            field=models.DateField(default=None),
        ),
    ]
