# Generated by Django 4.2.2 on 2023-10-31 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
