# Generated by Django 4.2.2 on 2023-07-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=70)),
                ('Specialisation', models.CharField(choices=[('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('General', 'General'), ('Orthopaedic', 'Orthopaedic'), ('Urology', 'Urology'), ('Pediatrics', 'Pediatrics'), ('gynecologists,', 'gynecologists,'), ('dentists', 'dentists')], max_length=70)),
                ('Contact_number', models.CharField(max_length=10)),
                ('Locations', models.CharField(max_length=80)),
                ('Enteredby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_schedule', models.DateField()),
                ('Time_of_schedule', models.DateTimeField()),
                ('Doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('Enteredby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
            ],
        ),
    ]
