# Generated by Django 4.2.2 on 2023-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_enteredby_alter_doctor_enteredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Time_of_schedule',
            field=models.TimeField(),
        ),
    ]
