# Generated by Django 4.2.2 on 2023-07-27 10:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_appointment_time_of_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date_of_schedule',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(6000000000)]),
        ),
    ]
