# Generated by Django 4.2.2 on 2023-07-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_appointment_date_of_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
