# Generated by Django 4.2.2 on 2023-07-28 16:44

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctor_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None, validators=[django.core.validators.RegexValidator(regex='[6-9][0-9]{9}')]),
        ),
    ]
