# Generated by Django 4.2.2 on 2023-07-28 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_alter_doctor_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='[6-9][0-9]{9}')]),
        ),
    ]
